golfball_current_phase = 0
golfball_current_strength = 2
golfball_air_puts = 1
golfball_max_air_puts = 1
golfball_friction = [0.97,0.985] //first is ground, second is underwater
golfball_bounce_power = 0.7
golfball_side_bounce_power = 0.82
golfball_current_angle = 0
golfball_still = false
golfball_grav_mult = 1
unicorn_power = false